name: "TNLWorlds"
version: "3.0.0"
api-version: "1.19"
author: "NonSwag"
website: "https://www.thenextlvl.net"
main: "net.nonswag.tnl.world.Worlds"
load: "POSTWORLD"
depend: ["TNLListener"]
provides: ["VoidGenerator", "FlatGenerator"]