name: "TNLWorlds"
version: "2.0"
api-version: "1.13"
author: "NonSwag"
website: "https://www.thenextlvl.net"
main: "net.nonswag.tnl.world.Worlds"
load: "POSTWORLD"
depend: ["TNLListener"]
commands:
  world:
